[Division Key]=[Division.Division Key]

[Business Unit Key] = [Tbl_Dim_Division.Business_Unit_Key]
[Business Unit Code] = [Tbl_Dim_Division.Business_Unit_Code]
[Business Unit] = [Tbl_Dim_Division.Business_Unit_Name]
[Technology Segment Code] = [Tbl_Dim_Division.Technology_Segment_Code]
[Technology Segment] = [Tbl_Dim_Division.Technology_Segment_Name]
[Division Code] = [Tbl_Dim_Division.Division_Code] 
[Division]=[Tbl_Dim_Division.Division_Name]
Writerecord