[Sales Office Key] = [Tbl_Dim_Sales_Region.Sales_Office_Code]
[Sales Office] = [Tbl_Dim_Sales_Region.Sales_Office_Name]
If [Tbl_Dim_Sales_Region.Regional_Currency_Code] = 'Rmb' Then
 [Rc Currency Key] = 'Cny'
Else
 [Rc Currency Key] = [Tbl_Dim_Sales_Region.Regional_Currency_Code]
End If
[Region]=[Tbl_Dim_Sales_Region.Sales_Region_Code]
[Subregion]=[Tbl_Dim_Sales_Region.Sales_Subregion_Code]
Writerecord