[date_valid_from]=[Exchange Rates FixedYearly.date_valid_from]
[date_valid_to]=[Exchange Rates FixedYearly.date_valid_to]
[curr_code_from]=[Exchange Rates FixedYearly.curr_code_from]
[curr_code_to]=[Exchange Rates FixedYearly.curr_code_to]
//[rate_with_factor]=FLOAT(FORMAT([Exchange Rates FixedYearly.rate_with_factor],'##,###,##0.000'))
[rate_with_factor]=[Exchange Rates FixedYearly.rate_with_factor]

WRITERECORD