[plant_code]=[SC-PriceIndex_Fact_Flag_update_2.plant_code]
[Division Key]=[SC-PriceIndex_Fact_Flag_update_2.Division Key]
[material_category_name]=[SC-PriceIndex_Fact_Flag_update_2.material_category_name]
[material_sub_category_name1]=[SC-PriceIndex_Fact_Flag_update_2.material_sub_category_name1]
[material_sub_category_name]=[SC-PriceIndex_Fact_Flag_update_2.material_sub_category_name]
[material_group_name1]=[SC-PriceIndex_Fact_Flag_update_2.material_group_name1]
[material_group_name]=[SC-PriceIndex_Fact_Flag_update_2.material_group_name]
[inco_term_code]=[SC-PriceIndex_Fact_Flag_update_2.inco_term_code]
[material_exclude_key]=[SC-PriceIndex_Fact_Flag_update_2.material_exclude_key]
[material_planner_code]=[SC-PriceIndex_Fact_Flag_update_2.material_planner_code]
[metal_key]=[SC-PriceIndex_Fact_Flag_update_2.metal_key]
[sourcing_manager_code]=[SC-PriceIndex_Fact_Flag_update_2.sourcing_manager_code]
[supplier_classification_code]=[SC-PriceIndex_Fact_Flag_update_2.supplier_classification_code]
[supplier_segmentation_code]=[SC-PriceIndex_Fact_Flag_update_2.supplier_segmentation_code]
[supplier_group_key]=[SC-PriceIndex_Fact_Flag_update_2.supplier_group_key]
[supplier_exclude_key]=[SC-PriceIndex_Fact_Flag_update_2.supplier_exclude_key]
[supplier_country_code]=[SC-PriceIndex_Fact_Flag_update_2.supplier_country_code]
[invoice_qty]=0.0

[uom_code]=[SC-PriceIndex_Fact_Flag_update_2.uom_code]
[supplier_code_invoice]=[SC-PriceIndex_Fact_Flag_update_2.supplier_code_invoice]

[debit_credit_flag]=[SC-PriceIndex_Fact_Flag_update_2.debit_credit_flag]
[tcurr_amnt]=0.0
[curr_code]=[SC-PriceIndex_Fact_Flag_update_2.curr_code]
//[rate]=[SC-PriceIndex_Fact_Flag_update_2.rate]
//[invoice_no]=[SC-PriceIndex_Fact_Flag_update_2.invoice_no]
//[invoice_pos]=[SC-PriceIndex_Fact_Flag_update_2.invoice_pos]
[subsequent_debitor_creditor]=[SC-PriceIndex_Fact_Flag_update_2.subsequent_debitor_creditor]
[baseline_date]=[SC-PriceIndex_Fact_Flag_update_2.baseline_date]
[no_of_days1]=[SC-PriceIndex_Fact_Flag_update_2.no_of_days1]
[disc_perc1]=[SC-PriceIndex_Fact_Flag_update_2.disc_perc1]
[no_of_days2]=[SC-PriceIndex_Fact_Flag_update_2.no_of_days2]
[disc_perc2]=[SC-PriceIndex_Fact_Flag_update_2.disc_perc2]

[correct_flag]=[SC-PriceIndex_Fact_Flag_update_2.correct_flag]
[active]=[SC-PriceIndex_Fact_Flag_update_2.active]
[tcurr_amnt_discounted]=0.0
[factor]=[SC-PriceIndex_Fact_Flag_update_2.factor]
[record_source_key]=[SC-PriceIndex_Fact_Flag_update_2.record_source_key]

[invoice_net]=0.0
[invoice_gross]=0.0
[rate_key]=[SC-PriceIndex_Fact_Flag_update_2.rate_key]
[rate_type_key]=[SC-PriceIndex_Fact_Flag_update_2.rate_type_key]
[curr_type_key]=[SC-PriceIndex_Fact_Flag_update_2.curr_type_key]
[invoice_currency_key]=[SC-PriceIndex_Fact_Flag_update_2.invoice_currency_key_DC]
//[invoice_exc_rate]=[SC-PriceIndex_Fact_Flag_update_2.invoice_exc_rate_DC]
[invoice_net_value]=0.0

[material_code]=[SC-PriceIndex_Fact_Flag_update_2.material_code]
[company_code]=[SC-PriceIndex_Fact_Flag_update_2.company_code]
[supplier_code]=[SC-PriceIndex_Fact_Flag_update_2.supplier_code]
//[posting_date]=[SC-PriceIndex_Fact_Flag_update_2.posting_date]
[posting_date]=DATEADD(Year,1,[SC-PriceIndex_Fact_Flag_update_2.posting_date])

[purchase_group_key]=[SC-PriceIndex_Fact_Flag_update_2.purchase_group_key]
[purchase_organisation_code]=[SC-PriceIndex_Fact_Flag_update_2.purchase_organisation_code]
[index_type_key]=[SC-PriceIndex_Fact_Flag_update_2.index_type_key]
[index_type_above_year_key]=[SC-PriceIndex_Fact_Flag_update_2.index_type_above_year_key]


[invoice_qty_Cumm]=0.0


/* 12 months - Previous whole year*/
[invoice_qty_12m]=0.0
[invoice_net_value_12m]=0.0

/*relations */
/*
[supplier_relation_key]=[SC-PriceIndex_Fact_Flag_update_2.supplier_relation_regular_key]
[plant_relation_key]=[SC-PriceIndex_Fact_Flag_update_2.plant_relation_neutral_key]
[company_relation_key]=[SC-PriceIndex_Fact_Flag_update_2.company_relation_regular_key]
*/


[invoice_gross_value]=0.0
[invoice_gross_value_Cumm]=0.0

[CurrRateKey]=[SC-PriceIndex_Fact_Flag_update_2.CurrRateKeyDC]

PRINT [SC-PriceIndex_Fact_Flag_update_2.posting_date]

WRITERECORD