[CustArea Key]=[S_Kunde.Firma] + '_' + [S_Kunde.Kunde] + '9200'
[Customer Key]=[S_Kunde.Kunde]
// Only 10 characters will get updated for source, which is ok
[Source]='I4-proAlpha'
[Comp Code Key]='9200'
[Sales Office Key]='9200'
[Sales Office]=[tbl_dim_sales_region.sales_office_name]
[Sales SubRegion]=[tbl_dim_sales_region.sales_subregion_code]
[Sales Region]=[tbl_dim_sales_region.sales_region_code]
[RC Currency Key]=[tbl_dim_sales_region.regional_currency_code]

WRITERECORD