[perakt]=[SQL_CCR_Fastnet_xomrv.perakt]
[vkod]=[SQL_CCR_Fastnet_xomrv.vkod]
[kurstyp]=[SQL_CCR_Fastnet_xomrv.kurstyp]
[enhet]=[SQL_CCR_Fastnet_xomrv.enhet]
[kurs]=[SQL_CCR_Fastnet_xomrv.kurs]
[Year]=SUBSTRING([SQL_CCR_Fastnet_xomrv.perakt],0,2)
[Month]=SUBSTRING([SQL_CCR_Fastnet_xomrv.perakt],2,4)
[Type]=SUBSTRING([SQL_CCR_Fastnet_xomrv.perakt],4,6)
[Source]=[SQL_CCR_Fastnet_xomrv.kurstyp]
[Exchange Rate]=[SQL_CCR_Fastnet_xomrv.kurs]
[Currency Key]=[SQL_CCR_Fastnet_xomrv.vkod]
WRITERECORD