[Division Key]=[Division.Division Key]

[Business Unit Key] = [tbl_dim_division.business_unit_key]
[Business Unit Code] = [tbl_dim_division.business_unit_code]
[Business Unit] = [tbl_dim_division.business_unit_name]
[Technology Code] = [tbl_dim_division.technology_code]
[Technology] = [tbl_dim_division.technology_name]
[Division Code] = [tbl_dim_division.business_unit_key] 
[Division]=[tbl_dim_division.technology_name]
WRITERECORD